In [13]:
from nba_api.stats.endpoints import leaguedashplayerstats
import pandas as pd
player_stats = leaguedashplayerstats.LeagueDashPlayerStats(season='2020-21', measure_type_detailed_defense='Advanced').get_data_frames()[0]
pd.set_option('display.max_columns', None)
player_stats.head()

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,MIN,E_OFF_RATING,OFF_RATING,sp_work_OFF_RATING,E_DEF_RATING,DEF_RATING,sp_work_DEF_RATING,E_NET_RATING,NET_RATING,sp_work_NET_RATING,AST_PCT,AST_TO,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,E_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,sp_work_PACE,PIE,POSS,FGM,FGA,FGM_PG,FGA_PG,FG_PCT,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,E_OFF_RATING_RANK,OFF_RATING_RANK,sp_work_OFF_RATING_RANK,E_DEF_RATING_RANK,DEF_RATING_RANK,sp_work_DEF_RATING_RANK,E_NET_RATING_RANK,NET_RATING_RANK,sp_work_NET_RATING_RANK,AST_PCT_RANK,AST_TO_RANK,AST_RATIO_RANK,OREB_PCT_RANK,DREB_PCT_RANK,REB_PCT_RANK,TM_TOV_PCT_RANK,E_TOV_PCT_RANK,EFG_PCT_RANK,TS_PCT_RANK,USG_PCT_RANK,E_USG_PCT_RANK,E_PACE_RANK,PACE_RANK,sp_work_PACE_RANK,PIE_RANK,FGM_RANK,FGA_RANK,FGM_PG_RANK,FGA_PG_RANK,FG_PCT_RANK
0,203932,Aaron Gordon,Aaron,1610612743,DEN,25.0,50,29,21,0.580,27.7,111.8,112.5,112.5,110.4,110.4,110.4,1.4,2.1,2.1,0.165,1.66,19.6,0.055,0.150,0.102,11.8,11.8,0.522,0.547,0.204,0.207,99.83,99.48,82.90,99.48,0.095,2868,231,499,4.6,10.0,0.463,238,158,258,167,135,139,133,133,307,291,291,179,170,170,147,269,158,139,199,172,402,397,275,304,152,156,406,421,421,212,154,153,134,127,216
1,1628988,Aaron Holiday,Aaron,1610612754,IND,24.0,66,30,36,0.455,17.8,110.2,110.1,110.1,109.9,110.3,110.3,0.2,-0.2,-0.2,0.139,1.86,18.5,0.012,0.060,0.036,9.9,10.0,0.467,0.503,0.189,0.193,104.48,104.34,86.95,104.34,0.057,2560,170,436,2.6,6.6,0.390,70,143,490,318,310,189,203,203,281,287,287,228,238,238,198,226,185,470,525,526,288,294,434,423,203,209,72,87,87,450,213,175,287,243,431
2,1630174,Aaron Nesmith,Aaron,1610612738,BOS,21.0,46,22,24,0.478,14.5,108.9,108.6,108.6,108.6,109.1,109.1,0.3,-0.5,-0.5,0.047,1.00,9.7,0.041,0.146,0.093,9.7,9.7,0.551,0.573,0.133,0.138,101.20,101.13,84.28,101.13,0.060,1409,78,178,1.7,3.9,0.438,268,252,309,286,376,229,255,255,198,228,228,226,255,255,496,424,458,204,209,210,274,278,184,214,444,442,295,290,290,440,343,341,386,382,288
3,1627846,Abdel Nader,Abdel,1610612756,PHX,27.0,24,16,8,0.667,14.8,106.6,106.7,106.7,103.2,101.7,101.7,3.4,5.0,5.0,0.078,1.00,11.2,0.020,0.151,0.088,11.2,11.2,0.569,0.605,0.183,0.189,102.30,102.96,85.80,102.96,0.092,757,57,116,2.4,4.8,0.491,417,331,76,79,370,318,315,315,52,48,48,132,95,95,390,424,414,362,194,231,363,363,129,113,228,231,199,152,152,231,370,378,310,323,141
4,1629690,Adam Mokoka,Adam,1610612741,CHI,22.0,14,3,11,0.214,4.0,85.1,83.2,83.2,93.4,90.3,90.3,-8.3,-7.1,-7.1,0.179,1.00,17.2,0.017,0.077,0.045,17.2,17.0,0.395,0.386,0.171,0.186,103.47,106.38,88.65,106.38,0.025,125,7,19,0.5,1.4,0.368,463,482,111,506,517,530,528,528,17,13,13,440,423,423,130,424,221,406,486,496,515,514,501,510,274,238,115,36,36,515,493,489,508,510,469

In [14]:
player_stats.columns
cols_using = ['PLAYER_ID', 'PLAYER_NAME', 'TEAM_ID', 'TEAM_ABBREVIATION',
       'AGE', 'GP_RANK','W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'E_OFF_RATING_RANK',
       'OFF_RATING_RANK', 'sp_work_OFF_RATING_RANK', 'E_DEF_RATING_RANK',
       'DEF_RATING_RANK', 'sp_work_DEF_RATING_RANK', 'E_NET_RATING_RANK',
       'NET_RATING_RANK', 'sp_work_NET_RATING_RANK', 'AST_PCT_RANK',
       'AST_TO_RANK', 'AST_RATIO_RANK', 'OREB_PCT_RANK', 'DREB_PCT_RANK',
       'REB_PCT_RANK', 'TM_TOV_PCT_RANK', 'E_TOV_PCT_RANK', 'EFG_PCT_RANK',
       'TS_PCT_RANK', 'USG_PCT_RANK', 'E_USG_PCT_RANK', 'E_PACE_RANK',
       'PACE_RANK', 'sp_work_PACE_RANK', 'PIE_RANK', 'FGM_RANK', 'FGA_RANK',
       'FGM_PG_RANK', 'FGA_PG_RANK', 'FG_PCT_RANK']

In [15]:
import os
import glob
player_df = pd.DataFrame()

main_folder_path = 'Teams'
for subfolder in os.listdir(main_folder_path):
    subfolder_path = os.path.join(main_folder_path, subfolder)
    if os.path.isdir(subfolder_path):
        print(f"Processing files in: {subfolder}")
        file_pattern = os.path.join(subfolder_path, '*.csv')
        for file_path in glob.glob(file_pattern):
            player_df = pd.concat([player_df, pd.read_csv(file_path)])

Processing files in: CHI
Processing files in: OKC
Processing files in: CHA
Processing files in: IND
Processing files in: DET
Processing files in: SAC
Processing files in: DEN
Processing files in: LAC
Processing files in: ATL
Processing files in: LAL
Processing files in: UTA
Processing files in: PHX
Processing files in: MIL
Processing files in: POR
Processing files in: TOR
Processing files in: NOP
Processing files in: SAS
Processing files in: HOU
Processing files in: GSW
Processing files in: WAS
Processing files in: BOS
Processing files in: DAL
Processing files in: BKN
Processing files in: ORL
Processing files in: NYK
Processing files in: MIN
Processing files in: CLE
Processing files in: PHI
Processing files in: MEM
Processing files in: MIA

In [16]:
player_df.shape

(12580, 28)

In [17]:
player_df.head()

,Unnamed: 0,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1,1627885.0,2018-19,0.0,1.610613e+09,CHI,25.0,73.0,11.0,1430.0,184.0,426.0,0.432,24.0,89.0,0.270,82.0,123.0,0.667,33.0,189.0,222.0,139.0,89.0,30.0,60.0,124.0,474.0
1,3,1626245.0,2018-19,0.0,1.610613e+09,CHI,26.0,60.0,0.0,746.0,95.0,179.0,0.531,0.0,4.0,0.000,50.0,73.0,0.685,79.0,139.0,218.0,37.0,11.0,7.0,33.0,69.0,240.0
2,2,1627789.0,2018-19,0.0,1.610613e+09,OKC,24.0,21.0,1.0,123.0,13.0,43.0,0.302,5.0,22.0,0.227,4.0,6.0,0.667,4.0,14.0,18.0,4.0,4.0,1.0,5.0,14.0,35.0
3,3,1627789.0,2018-19,0.0,1.610613e+09,CHI,24.0,29.0,6.0,546.0,69.0,175.0,0.394,31.0,94.0,0.330,27.0,35.0,0.771,7.0,72.0,79.0,22.0,15.0,7.0,16.0,59.0,196.0
4,4,1627789.0,2018-19,0.0,0.000000e+00,TOT,24.0,50.0,7.0,669.0,82.0,218.0,0.376,36.0,116.0,0.310,31.0,41.0,0.756,11.0,86.0,97.0,26.0,19.0,8.0,21.0,73.0,231.0

In [18]:
player_df = player_df.drop(['Unnamed: 0'], axis=1)
player_df['TEAM_ID'] = player_df['TEAM_ID'].apply(lambda x: str(x)[:-2])
player_df.head()

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1627885.0,2018-19,0.0,1610612741,CHI,25.0,73.0,11.0,1430.0,184.0,426.0,0.432,24.0,89.0,0.270,82.0,123.0,0.667,33.0,189.0,222.0,139.0,89.0,30.0,60.0,124.0,474.0
1,1626245.0,2018-19,0.0,1610612741,CHI,26.0,60.0,0.0,746.0,95.0,179.0,0.531,0.0,4.0,0.000,50.0,73.0,0.685,79.0,139.0,218.0,37.0,11.0,7.0,33.0,69.0,240.0
2,1627789.0,2018-19,0.0,1610612760,OKC,24.0,21.0,1.0,123.0,13.0,43.0,0.302,5.0,22.0,0.227,4.0,6.0,0.667,4.0,14.0,18.0,4.0,4.0,1.0,5.0,14.0,35.0
3,1627789.0,2018-19,0.0,1610612741,CHI,24.0,29.0,6.0,546.0,69.0,175.0,0.394,31.0,94.0,0.330,27.0,35.0,0.771,7.0,72.0,79.0,22.0,15.0,7.0,16.0,59.0,196.0
4,1627789.0,2018-19,0.0,0,TOT,24.0,50.0,7.0,669.0,82.0,218.0,0.376,36.0,116.0,0.310,31.0,41.0,0.756,11.0,86.0,97.0,26.0,19.0,8.0,21.0,73.0,231.0

In [20]:
player_df['PLAYER_ID'] = player_df['PLAYER_ID'].apply(lambda x: str(x)[:-2])
player_df.head()

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1627885,2018-19,0.0,1610612741,CHI,25.0,73.0,11.0,1430.0,184.0,426.0,0.432,24.0,89.0,0.270,82.0,123.0,0.667,33.0,189.0,222.0,139.0,89.0,30.0,60.0,124.0,474.0
1,1626245,2018-19,0.0,1610612741,CHI,26.0,60.0,0.0,746.0,95.0,179.0,0.531,0.0,4.0,0.000,50.0,73.0,0.685,79.0,139.0,218.0,37.0,11.0,7.0,33.0,69.0,240.0
2,1627789,2018-19,0.0,1610612760,OKC,24.0,21.0,1.0,123.0,13.0,43.0,0.302,5.0,22.0,0.227,4.0,6.0,0.667,4.0,14.0,18.0,4.0,4.0,1.0,5.0,14.0,35.0
3,1627789,2018-19,0.0,1610612741,CHI,24.0,29.0,6.0,546.0,69.0,175.0,0.394,31.0,94.0,0.330,27.0,35.0,0.771,7.0,72.0,79.0,22.0,15.0,7.0,16.0,59.0,196.0
4,1627789,2018-19,0.0,0,TOT,24.0,50.0,7.0,669.0,82.0,218.0,0.376,36.0,116.0,0.310,31.0,41.0,0.756,11.0,86.0,97.0,26.0,19.0,8.0,21.0,73.0,231.0

In [26]:
player_stats = pd.DataFrame()
for year in range(2000, 2023):
    season = f'{year}-{str(year+1)[-2:]}'
    temp = leaguedashplayerstats.LeagueDashPlayerStats(season=season, measure_type_detailed_defense='Advanced').get_data_frames()[0]
    temp = temp[cols_using]
    temp['SEASON_ID'] = [season for _ in range(temp.shape[0])]
    player_stats = pd.concat([player_stats, temp])
    print(year)

2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022

In [27]:
player_stats.head()

,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,E_OFF_RATING_RANK,OFF_RATING_RANK,sp_work_OFF_RATING_RANK,E_DEF_RATING_RANK,DEF_RATING_RANK,sp_work_DEF_RATING_RANK,E_NET_RATING_RANK,NET_RATING_RANK,sp_work_NET_RATING_RANK,AST_PCT_RANK,AST_TO_RANK,AST_RATIO_RANK,OREB_PCT_RANK,DREB_PCT_RANK,REB_PCT_RANK,TM_TOV_PCT_RANK,E_TOV_PCT_RANK,EFG_PCT_RANK,TS_PCT_RANK,USG_PCT_RANK,E_USG_PCT_RANK,E_PACE_RANK,PACE_RANK,sp_work_PACE_RANK,PIE_RANK,FGM_RANK,FGA_RANK,FGM_PG_RANK,FGA_PG_RANK,FG_PCT_RANK,SEASON_ID
0,920,A.C. Green,1610612748,MIA,37.0,2,38,262,130,253,350,349,349,16,17,17,107,95,95,374,283,336,126,136,131,116,118,278,258,359,358,417,412,412,158,213,216,281,286,171,2000-01
1,2062,A.J. Guyton,1610612741,CHI,23.0,334,381,204,419,228,402,376,376,346,318,318,404,397,397,107,38,105,371,427,428,53,55,178,252,254,260,408,416,416,282,291,285,222,208,293,2000-01
2,243,Aaron McKie,1610612755,PHI,28.0,120,31,178,57,89,110,103,103,66,65,65,39,29,29,57,111,67,385,227,272,348,343,60,73,183,186,282,289,289,68,80,92,93,102,106,2000-01
3,1425,Aaron Williams,1610612751,NJN,29.0,2,223,427,358,115,324,288,288,373,378,378,373,357,357,316,323,333,85,74,79,293,292,241,119,215,224,262,274,274,151,105,109,133,140,141,2000-01
4,228,Adam Keefe,1610612744,GSW,31.0,192,318,420,407,317,357,353,353,336,365,365,372,387,387,328,272,216,61,139,111,356,357,349,347,408,410,151,160,160,336,306,300,369,374,300,2000-01

In [28]:
player_stats.shape

(11087, 41)

In [30]:
player_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12580 entries, 0 to 18
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   PLAYER_ID          12580 non-null  object
 1   SEASON_ID          12580 non-null  object
 2   LEAGUE_ID          12580 non-null  float64
 3   TEAM_ID            12580 non-null  object
 4   TEAM_ABBREVIATION  12580 non-null  object
 5   PLAYER_AGE         12580 non-null  float64
 6   GP                 12580 non-null  float64
 7   GS                 12580 non-null  float64
 8   MIN                12580 non-null  float64
 9   FGM                12580 non-null  float64
 10  FGA                12580 non-null  float64
 11  FG_PCT             12580 non-null  float64
 12  FG3M               12580 non-null  float64
 13  FG3A               12580 non-null  float64
 14  FG3_PCT            12580 non-null  float64
 15  FTM                12580 non-null  float64
 16  FTA                12580 non-null  float64
 17  FT_PCT             12580 non-null  float64
 18  OREB               12580 non-null  float64
 19  DREB               12580 non-null  float64
 20  REB                12580 non-null  float64
 21  AST                12580 non-null  float64
 22  STL                12580 non-null  float64
 23  BLK                12580 non-null  float64
 24  TOV                12580 non-null  float64
 25  PF                 12580 non-null  float64
 26  PTS                12580 non-null  float64
dtypes: float64(23), object(4)
memory usage: 2.7+ MB

In [31]:
player_stats.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11087 entries, 0 to 538
Data columns (total 41 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   PLAYER_ID                11087 non-null  int64
 1   PLAYER_NAME              11087 non-null  object
 2   TEAM_ID                  11087 non-null  int64
 3   TEAM_ABBREVIATION        11087 non-null  object
 4   AGE                      11087 non-null  float64
 5   GP_RANK                  11087 non-null  int64
 6   W_RANK                   11087 non-null  int64
 7   L_RANK                   11087 non-null  int64
 8   W_PCT_RANK               11087 non-null  int64
 9   MIN_RANK                 11087 non-null  int64
 10  E_OFF_RATING_RANK        11087 non-null  int64
 11  OFF_RATING_RANK          11087 non-null  int64
 12  sp_work_OFF_RATING_RANK  11087 non-null  int64
 13  E_DEF_RATING_RANK        11087 non-null  int64
 14  DEF_RATING_RANK          11087 non-null  int64
 15  sp_work_DEF_RATING_RANK  11087 non-null  int64
 16  E_NET_RATING_RANK        11087 non-null  int64
 17  NET_RATING_RANK          11087 non-null  int64
 18  sp_work_NET_RATING_RANK  11087 non-null  int64
 19  AST_PCT_RANK             11087 non-null  int64
 20  AST_TO_RANK              11087 non-null  int64
 21  AST_RATIO_RANK           11087 non-null  int64
 22  OREB_PCT_RANK            11087 non-null  int64
 23  DREB_PCT_RANK            11087 non-null  int64
 24  REB_PCT_RANK             11087 non-null  int64
 25  TM_TOV_PCT_RANK          11087 non-null  int64
 26  E_TOV_PCT_RANK           11087 non-null  int64
 27  EFG_PCT_RANK             11087 non-null  int64
 28  TS_PCT_RANK              11087 non-null  int64
 29  USG_PCT_RANK             11087 non-null  int64
 30  E_USG_PCT_RANK           11087 non-null  int64
 31  E_PACE_RANK              11087 non-null  int64
 32  PACE_RANK                11087 non-null  int64
 33  sp_work_PACE_RANK        11087 non-null  int64
 34  PIE_RANK                 11087 non-null  int64
 35  FGM_RANK                 11087 non-null  int64
 36  FGA_RANK                 11087 non-null  int64
 37  FGM_PG_RANK              11087 non-null  int64
 38  FGA_PG_RANK              11087 non-null  int64
 39  FG_PCT_RANK              11087 non-null  int64
 40  SEASON_ID                11087 non-null  object
dtypes: float64(1), int64(37), object(3)
memory usage: 3.6+ MB

In [32]:
player_stats['PLAYER_ID'] = player_stats['PLAYER_ID'].astype(str)

In [33]:
player_df = pd.merge(left=player_df, right=player_stats, on=['PLAYER_ID', 'SEASON_ID'], how='left')

In [36]:
player_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12580 entries, 0 to 12579
Data columns (total 66 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   PLAYER_ID                12580 non-null  object
 1   SEASON_ID                12580 non-null  object
 2   LEAGUE_ID                12580 non-null  float64
 3   TEAM_ID_x                12580 non-null  object
 4   TEAM_ABBREVIATION_x      12580 non-null  object
 5   PLAYER_AGE               12580 non-null  float64
 6   GP                       12580 non-null  float64
 7   GS                       12580 non-null  float64
 8   MIN                      12580 non-null  float64
 9   FGM                      12580 non-null  float64
 10  FGA                      12580 non-null  float64
 11  FG_PCT                   12580 non-null  float64
 12  FG3M                     12580 non-null  float64
 13  FG3A                     12580 non-null  float64
 14  FG3_PCT                  12580 non-null  float64
 15  FTM                      12580 non-null  float64
 16  FTA                      12580 non-null  float64
 17  FT_PCT                   12580 non-null  float64
 18  OREB                     12580 non-null  float64
 19  DREB                     12580 non-null  float64
 20  REB                      12580 non-null  float64
 21  AST                      12580 non-null  float64
 22  STL                      12580 non-null  float64
 23  BLK                      12580 non-null  float64
 24  TOV                      12580 non-null  float64
 25  PF                       12580 non-null  float64
 26  PTS                      12580 non-null  float64
 27  PLAYER_NAME              12580 non-null  object
 28  TEAM_ID_y                12580 non-null  int64
 29  TEAM_ABBREVIATION_y      12580 non-null  object
 30  AGE                      12580 non-null  float64
 31  GP_RANK                  12580 non-null  int64
 32  W_RANK                   12580 non-null  int64
 33  L_RANK                   12580 non-null  int64
 34  W_PCT_RANK               12580 non-null  int64
 35  MIN_RANK                 12580 non-null  int64
 36  E_OFF_RATING_RANK        12580 non-null  int64
 37  OFF_RATING_RANK          12580 non-null  int64
 38  sp_work_OFF_RATING_RANK  12580 non-null  int64
 39  E_DEF_RATING_RANK        12580 non-null  int64
 40  DEF_RATING_RANK          12580 non-null  int64
 41  sp_work_DEF_RATING_RANK  12580 non-null  int64
 42  E_NET_RATING_RANK        12580 non-null  int64
 43  NET_RATING_RANK          12580 non-null  int64
 44  sp_work_NET_RATING_RANK  12580 non-null  int64
 45  AST_PCT_RANK             12580 non-null  int64
 46  AST_TO_RANK              12580 non-null  int64
 47  AST_RATIO_RANK           12580 non-null  int64
 48  OREB_PCT_RANK            12580 non-null  int64
 49  DREB_PCT_RANK            12580 non-null  int64
 50  REB_PCT_RANK             12580 non-null  int64
 51  TM_TOV_PCT_RANK          12580 non-null  int64
 52  E_TOV_PCT_RANK           12580 non-null  int64
 53  EFG_PCT_RANK             12580 non-null  int64
 54  TS_PCT_RANK              12580 non-null  int64
 55  USG_PCT_RANK             12580 non-null  int64
 56  E_USG_PCT_RANK           12580 non-null  int64
 57  E_PACE_RANK              12580 non-null  int64
 58  PACE_RANK                12580 non-null  int64
 59  sp_work_PACE_RANK        12580 non-null  int64
 60  PIE_RANK                 12580 non-null  int64
 61  FGM_RANK                 12580 non-null  int64
 62  FGA_RANK                 12580 non-null  int64
 63  FGM_PG_RANK              12580 non-null  int64
 64  FGA_PG_RANK              12580 non-null  int64
 65  FG_PCT_RANK              12580 non-null  int64
dtypes: float64(24), int64(36), object(6)
memory usage: 6.3+ MB

In [37]:
player_stats.columns

Index(['PLAYER_ID', 'PLAYER_NAME', 'TEAM_ID', 'TEAM_ABBREVIATION', 'AGE',
       'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK',
       'E_OFF_RATING_RANK', 'OFF_RATING_RANK', 'sp_work_OFF_RATING_RANK',
       'E_DEF_RATING_RANK', 'DEF_RATING_RANK', 'sp_work_DEF_RATING_RANK',
       'E_NET_RATING_RANK', 'NET_RATING_RANK', 'sp_work_NET_RATING_RANK',
       'AST_PCT_RANK', 'AST_TO_RANK', 'AST_RATIO_RANK', 'OREB_PCT_RANK',
       'DREB_PCT_RANK', 'REB_PCT_RANK', 'TM_TOV_PCT_RANK', 'E_TOV_PCT_RANK',
       'EFG_PCT_RANK', 'TS_PCT_RANK', 'USG_PCT_RANK', 'E_USG_PCT_RANK',
       'E_PACE_RANK', 'PACE_RANK', 'sp_work_PACE_RANK', 'PIE_RANK', 'FGM_RANK',
       'FGA_RANK', 'FGM_PG_RANK', 'FGA_PG_RANK', 'FG_PCT_RANK', 'SEASON_ID'],
      dtype='object')

In [38]:
player_stats.to_csv('all_players.csv')